2019-12-11 22:33:34 WARN  ConnectionUtil:39 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:37)
	at com.revature.repositories.EmployeeDAOImpl.insert(EmployeeDAOImpl.java:82)
	at com.revature.services.EmployeeService.insert(EmployeeService.java:23)
	at com.revature.main.CreateAccount.createAccount(CreateAccount.java:20)
	at com.revature.main.HaveAccount.haveAccount(HaveAccount.java:43)
	at com.revature.main.Driver.main(Driver.java:8)
2019-12-12 09:40:02 WARN  Login:32 - Unable to find Username
2019-12-12 09:41:15 WARN  Login:34 - Unable to find Username
2019-12-12 09:44:26 WARN  Login:34 - Unable to find Username
2019-12-12 09:44:55 WARN  Login:34 - Unable to find Username
2019-12-12 09:47:00 WARN  Login:34 - Unable to find Username
2019-12-12 09:49:04 WARN  Login:34 - Unable to find Username
2019-12-12 09:51:32 WARN  Login:34 - Unable to find Username
2019-12-12 09:52:30 WARN  Login:35 - Unable to find Username
2019-12-14 13:02:53 WARN  UserDAOImpl:76 - Unable to create account
org.postgresql.util.PSQLException: No value specified for parameter 4.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.createAccount(UserDAOImpl.java:72)
	at com.revature.services.UserService.createAccount(UserService.java:39)
	at com.revature.login.CreateAccount.createAccount(CreateAccount.java:24)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:42)
	at com.revature.login.Driver.main(Driver.java:8)
2019-12-14 13:03:50 WARN  UserDAOImpl:76 - Unable to create account
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pkey"
  Detail: Key (user_id)=(1) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.createAccount(UserDAOImpl.java:72)
	at com.revature.services.UserService.createAccount(UserService.java:39)
	at com.revature.login.CreateAccount.createAccount(CreateAccount.java:24)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:42)
	at com.revature.login.Driver.main(Driver.java:8)
2019-12-14 13:09:56 WARN  UserDAOImpl:76 - Unable to create account
org.postgresql.util.PSQLException: ERROR: column "user_id" is of type integer but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 84
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.createAccount(UserDAOImpl.java:72)
	at com.revature.services.UserService.createAccount(UserService.java:39)
	at com.revature.login.CreateAccount.createAccount(CreateAccount.java:24)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:42)
	at com.revature.login.Driver.main(Driver.java:8)
2019-12-14 13:18:12 WARN  UserDAOImpl:75 - Unable to create account
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pkey"
  Detail: Key (user_id)=(2) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.createAccount(UserDAOImpl.java:71)
	at com.revature.services.UserService.createAccount(UserService.java:39)
	at com.revature.login.CreateAccount.createAccount(CreateAccount.java:24)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:42)
	at com.revature.login.Driver.main(Driver.java:8)
2019-12-14 13:20:30 WARN  UserDAOImpl:75 - Unable to create account
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pkey"
  Detail: Key (user_id)=(3) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.createAccount(UserDAOImpl.java:71)
	at com.revature.services.UserService.createAccount(UserService.java:39)
	at com.revature.login.CreateAccount.createAccount(CreateAccount.java:24)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:42)
	at com.revature.login.Driver.main(Driver.java:8)
2019-12-14 13:21:26 WARN  UserDAOImpl:75 - Unable to create account
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_pkey"
  Detail: Key (user_id)=(4) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.createAccount(UserDAOImpl.java:71)
	at com.revature.services.UserService.createAccount(UserService.java:39)
	at com.revature.login.CreateAccount.createAccount(CreateAccount.java:24)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:42)
	at com.revature.login.Driver.main(Driver.java:8)
2019-12-14 13:31:11 WARN  UserDAOImpl:75 - Unable to create account
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.createAccount(UserDAOImpl.java:71)
	at com.revature.services.UserService.createAccount(UserService.java:39)
	at com.revature.login.CreateAccount.createAccount(CreateAccount.java:24)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:40)
	at com.revature.login.Driver.main(Driver.java:8)
2019-12-14 14:16:05 WARN  Login:42 - Unable to find Account
2019-12-14 14:16:33 WARN  Login:42 - Unable to find Account
2019-12-14 14:17:19 WARN  Login:43 - Unable to find Account
2019-12-14 14:19:26 WARN  Login:43 - Unable to find Account
2019-12-14 14:20:02 WARN  Login:43 - Unable to find Account
2019-12-14 14:20:51 WARN  Login:44 - Unable to find Account
2019-12-14 14:21:19 WARN  Login:43 - Unable to find Account
2019-12-14 15:05:03 WARN  Login:54 - Unable to find Account
2019-12-14 15:06:28 WARN  Login:53 - Unable to find Account
2019-12-14 15:14:51 WARN  Login:52 - Unable to find Account
2019-12-14 15:15:14 WARN  Login:53 - Unable to find Account
2019-12-14 15:15:57 WARN  Login:53 - Unable to find Account
2019-12-14 15:16:45 WARN  Login:54 - Unable to find Account
2019-12-14 15:17:40 WARN  Login:54 - Unable to find Account
2019-12-14 15:26:49 WARN  Login:55 - Unable to find Account
2019-12-14 15:28:07 WARN  Login:56 - Unable to find Account
2019-12-15 14:45:23 WARN  UserDAOImpl:37 - Jee Wilikers Batman we're not gonna pass
2019-12-15 14:46:20 WARN  UserDAOImpl:37 - Jee Wilikers Batman we're not gonna pass
2019-12-15 14:48:36 WARN  UserDAOImpl:39 - Jee Wilikers Batman we're not gonna pass
2019-12-15 14:50:13 WARN  UserDAOImpl:38 - Jee Wilikers Batman we're not gonna pass
2019-12-15 15:16:39 WARN  UserDAOImpl:41 - Jee Wilikers Batman we're not gonna pass
2019-12-15 15:20:16 WARN  UserDAOImpl:42 - Jee Wilikers Batman we're not gonna pass
2019-12-15 15:21:45 WARN  UserDAOImpl:42 - Jee Wilikers Batman we're not gonna pass
2019-12-15 15:24:43 WARN  UserDAOImpl:43 - Jee Wilikers Batman we're not gonna pass
2019-12-15 15:26:01 WARN  UserDAOImpl:44 - Jee Wilikers Batman we're not gonna pass
2019-12-15 15:30:04 WARN  UserDAOImpl:44 - Jee Wilikers Batman we're not gonna pass
2019-12-15 15:31:00 WARN  UserDAOImpl:44 - Jee Wilikers Batman we're not gonna pass
2019-12-15 16:14:57 WARN  UserDAOImpl:58 - Jee Wilikers Batman we're not gonna pass
2019-12-15 16:17:24 WARN  UserDAOImpl:58 - Jee Wilikers Batman we're not gonna pass
2019-12-15 16:18:13 WARN  UserDAOImpl:58 - Jee Wilikers Batman we're not gonna pass
2019-12-15 16:18:50 WARN  UserDAOImpl:59 - Jee Wilikers Batman we're not gonna pass
2019-12-15 17:12:28 WARN  UserDAOImpl:89 - Jee Wilikers Batman we're not gonna pass
2019-12-15 17:14:05 WARN  UserDAOImpl:87 - Jee Wilikers Batman we're not gonna pass
2019-12-16 09:55:42 WARN  Login:58 - Unable to find Account
2019-12-16 09:56:27 WARN  Login:58 - Unable to find Account
2019-12-16 09:57:07 WARN  Login:58 - Unable to find Account
org.postgresql.util.PSQLException: Can't use query methods that take a query string on a PreparedStatement.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:95)
	at com.revature.login.Login.loginAccount(Login.java:41)
	at com.revature.login.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.login.Driver.main(Driver.java:12)
2019-12-16 11:53:39 WARN  LoggedIn:33 - SQL exception
org.postgresql.util.PSQLException: Can't use query methods that take a query string on a PreparedStatement.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:95)
	at com.revature.LoggedIn.loggedIn(LoggedIn.java:26)
	at com.revature.Login.loginAccount(Login.java:45)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:8)
2019-12-16 21:03:11 WARN  EmployeeDAOImpl:48 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name emp_id was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:34)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:16)
	at com.revature.EmployeeLoggedIn.loggedIn(EmployeeLoggedIn.java:22)
	at com.revature.repositories.UserDAOImpl.employeeCheck(UserDAOImpl.java:281)
	at com.revature.repositories.UserDAOImpl.logIn(UserDAOImpl.java:244)
	at com.revature.services.UserService.logIn(UserService.java:32)
	at com.revature.Login.loginAccount(Login.java:28)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:8)
2019-12-16 21:08:00 WARN  EmployeeDAOImpl:49 - Unable to retrieve all users
org.postgresql.util.PSQLException: The column name emp_id was not found in this ResultSet.
	at org.postgresql.jdbc.PgResultSet.findColumn(PgResultSet.java:2607)
	at org.postgresql.jdbc.PgResultSet.getInt(PgResultSet.java:2498)
	at com.revature.repositories.EmployeeDAOImpl.findAll(EmployeeDAOImpl.java:34)
	at com.revature.services.EmployeeService.findAll(EmployeeService.java:16)
	at com.revature.EmployeeLoggedIn.loggedIn(EmployeeLoggedIn.java:22)
	at com.revature.repositories.UserDAOImpl.employeeCheck(UserDAOImpl.java:281)
	at com.revature.repositories.UserDAOImpl.logIn(UserDAOImpl.java:244)
	at com.revature.services.UserService.logIn(UserService.java:32)
	at com.revature.Login.loginAccount(Login.java:28)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 00:13:15 WARN  UserDAOImpl:295 - Something went wrong
org.postgresql.util.PSQLException: ERROR: column "user_name" does not exist
  Position: 45
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.accountApproved(UserDAOImpl.java:287)
	at com.revature.services.UserService.accountApproved(UserService.java:35)
	at com.revature.UserLoggedIn.loggedIn(UserLoggedIn.java:27)
	at com.revature.repositories.UserDAOImpl.employeeCheck(UserDAOImpl.java:269)
	at com.revature.repositories.UserDAOImpl.logIn(UserDAOImpl.java:230)
	at com.revature.services.UserService.logIn(UserService.java:32)
	at com.revature.Login.loginAccount(Login.java:28)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:21:33 WARN  UserDAOImpl:138 - Jee Wilikers Batman we're not gonna pass
org.postgresql.util.PSQLException: No results were returned by the query.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at com.revature.repositories.UserDAOImpl.transfer(UserDAOImpl.java:124)
	at com.revature.services.UserService.transfer(UserService.java:21)
	at com.revature.UserLoggedIn.loggedIn(UserLoggedIn.java:59)
	at com.revature.repositories.UserDAOImpl.employeeCheck(UserDAOImpl.java:251)
	at com.revature.repositories.UserDAOImpl.logIn(UserDAOImpl.java:213)
	at com.revature.services.UserService.logIn(UserService.java:32)
	at com.revature.Login.loginAccount(Login.java:36)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:22:39 WARN  UserDAOImpl:138 - Jee Wilikers Batman we're not gonna pass
org.postgresql.util.PSQLException: No results were returned by the query.
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at com.revature.repositories.UserDAOImpl.transfer(UserDAOImpl.java:124)
	at com.revature.services.UserService.transfer(UserService.java:21)
	at com.revature.UserLoggedIn.loggedIn(UserLoggedIn.java:59)
	at com.revature.repositories.UserDAOImpl.employeeCheck(UserDAOImpl.java:251)
	at com.revature.repositories.UserDAOImpl.logIn(UserDAOImpl.java:213)
	at com.revature.services.UserService.logIn(UserService.java:32)
	at com.revature.Login.loginAccount(Login.java:36)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 13:07:37 WARN  UserDAOImpl:263 - Something went wrong
org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 175
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.checkFunds(UserDAOImpl.java:252)
	at com.revature.services.UserService.checkFunds(UserService.java:41)
	at com.revature.AdminLoggedIn.loggedIn(AdminLoggedIn.java:69)
	at com.revature.AdminLoggedIn.loggedIn(AdminLoggedIn.java:76)
	at com.revature.repositories.UserDAOImpl.employeeCheck(UserDAOImpl.java:185)
	at com.revature.repositories.UserDAOImpl.logIn(UserDAOImpl.java:152)
	at com.revature.services.UserService.logIn(UserService.java:32)
	at com.revature.Login.loginAccount(Login.java:36)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:9)
2019-12-17 14:32:36 WARN  UserDAOImpl:263 - Something went wrong
org.postgresql.util.PSQLException: ERROR: operator does not exist: integer = character varying
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 175
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.checkFunds(UserDAOImpl.java:252)
	at com.revature.services.UserService.checkFunds(UserService.java:41)
	at com.revature.AdminLoggedIn.loggedIn(AdminLoggedIn.java:69)
	at com.revature.AdminLoggedIn.loggedIn(AdminLoggedIn.java:76)
	at com.revature.repositories.UserDAOImpl.employeeCheck(UserDAOImpl.java:185)
	at com.revature.repositories.UserDAOImpl.logIn(UserDAOImpl.java:152)
	at com.revature.services.UserService.logIn(UserService.java:32)
	at com.revature.Login.loginAccount(Login.java:36)
	at com.revature.HaveAccount.haveAccount(HaveAccount.java:33)
	at com.revature.Driver.main(Driver.java:9)
2019-12-17 14:47:55 INFO  UserDAOImpl:42 - 500 was added to temp1's Checking account
2019-12-17 14:48:33 INFO  UserDAOImpl:64 - 500 was removed from temp1's Checking account
2019-12-17 14:48:33 INFO  UserDAOImpl:42 - 500 was added to temp1's Savings account
2019-12-18 05:30:05 INFO  UserDAOImpl:42 - 500 was added to temp1's Checking account
2019-12-18 05:30:47 INFO  UserDAOImpl:42 - 500 was added to temp1's Checking account
2019-12-18 06:37:58 INFO  UserDAOImpl:42 - 500 was added to temp1's Checking account
